version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped
    ports:
      - "2181:2181"
    networks:
      - kafka-server

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_RESTART_DELAY: 5
      KAFKA_RESTART_ATTEMPTS: 10
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://kafka:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - kafka-server

  sec:
    build: './saga_execution_controller'
    container_name: sec
    restart: unless-stopped
    depends_on:
      - kafka
    environment:
      MONGOURI: mongodb+srv://ra115408:henriqueh1515@cluster0.y29zv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      MONGODATABASE: Cluster0
      KAFKAHOST: kafka:9092
    networks:
      - kafka-server

  api-gateway:
    build: './main_api'
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      MONGOURI: mongodb+srv://ra115408:henriqueh1515@cluster0.y29zv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      MONGODATABASE: Cluster0
      KAFKAHOST: kafka:9092
      GIN_MODE: release
    networks:
      - kafka-server

  inventory-service:
    build: './inventory_service'
    container_name: inventory-service
    restart: unless-stopped
    depends_on:
      - kafka
    environment:
      MONGOURI: mongodb+srv://ra115408:henriqueh1515@cluster0.y29zv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      MONGODATABASE: Cluster0
      KAFKAHOST: kafka:9092
    networks:
      - kafka-server

  payment-service:
    build: './payment_service'
    container_name: payment-service
    restart: unless-stopped
    depends_on:
      - kafka
    environment:
      MONGOURI: mongodb+srv://ra115408:henriqueh1515@cluster0.y29zv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      MONGODATABASE: Cluster0
      KAFKAHOST: kafka:9092
    networks:
      - kafka-server

  shipping-service:
    build: './shipping_service'
    container_name: shipping-service
    restart: unless-stopped
    depends_on:
      - kafka
    environment:
      MONGOURI: mongodb+srv://ra115408:henriqueh1515@cluster0.y29zv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      MONGODATABASE: Cluster0
      KAFKAHOST: kafka:9092
    networks:
      - kafka-server

networks:
  kafka-server:
    driver: bridge
